### ISSUE TITLE
Utils package tree shaking

### ISSUE THREAD

**Issue by alexandre-abrioux** [RequestNetwork/requestNetwork#1015]
## Issue

The `utils` package makes use of a default export, meaning that user code applications have to import the whole package even when using a small portion of it:
https://github.com/RequestNetwork/requestNetwork/blob/8ff76906005ed42e7624e73d7e2b579731508a0d/packages/utils/src/index.ts#L16-L28

## Ideas for improvement

- Replace the default export with named exports. This will allow for better tree shaking, lowering the build size of user code applications.
- Enforce the [no-default-export](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-default-export.md) ESLint rule.

**Comment by b4s36t4** [comment]
@alexandre-abrioux would love to work on this.

**Comment by MantisClone** [comment]
Hi, @b4s36t4 Thank you for your interest. This task has already been assigned to someone else, but I invite you to keep an eye on our [open bounties in DeWork](https://app.dework.xyz/request-network/development-56861/view/open-tasks-lbdt9jou) for future opportunities.
