### ISSUE TITLE
Allow DataAccess injection on HttpRequestNetwork

### ISSUE THREAD

**Issue by MantisClone** [RequestNetwork/requestNetwork#1047]
# Problem

Today, when instantiating instances of `HttpRequestNetwork` in the `request-client-js` package, we use mock storage by setting `useMockStorage=true`. However, there are times when it's important to demonstrate that the code works with two separate `RequestNetwork` instances using shared `DataAccess` and `Storage` layers. For example, the new `addStakeholders` feature #1025. 

# Feature Request

Change the `HttpRequestNetwork` constructor to allow injecting a `DataAccess` instance.

**Comment by benjlevesque** [comment]
You can use [RequestNetworkBase](https://github.com/RequestNetwork/requestNetwork/blob/master/packages/request-client.js/src/index.ts#LL14C9-L14C9) for this. The `RequestNetwork` class has more defaults than the Base, but it's basically the same thing

**Comment by MantisClone** [comment]
Okay, I'll convert the add stakeholders usage example to use RequestNetworkBase.
