### ISSUE TITLE
Unskip payment detection test

### ISSUE THREAD

**Issue by alexandre-abrioux** [RequestNetwork/requestNetwork#1082]
As a result of TheGraph deprecating its Rinkeby API, our CI broke, and it was quickly patched today in https://github.com/RequestNetwork/requestNetwork/pull/1080.

A test was marked as skipped.
It needs to be reintroduced with proper data from Goerli, and, if possible, by mocking all calls made to TheGraph hosted service:
https://github.com/RequestNetwork/requestNetwork/blob/27aaa1f36fe27563aa0aecd309be4387e07f4777/packages/payment-detection/test/eth/input-data.test.ts#L177-L178

---

Migrated from Asana: https://app.asana.com/0/1203912381456855/1205300974037114/f

**Comment by MantisClone** [comment]
Do this when #1130

**Comment by MantisClone** [comment]
We're going to deprecate the input data payment method. So closing this as unplanned.
