### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by MantisClone** [RequestNetwork/requestNetwork#1092]
# Problem

Usually, a flaky test fails due to timeout, like so:

```
BTC detection test-suite › Can create a BTC mainnet payment provider request and detect the payment

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:
```

# Examples
* [nightly](https://app.circleci.com/pipelines/github/RequestNetwork/requestNetwork/8075/workflows/59100f1f-adc9-4372-8d97-25d7e50ea78d/jobs/131403)
* [payment-processor](https://app.circleci.com/pipelines/github/RequestNetwork/requestNetwork/8421/workflows/74d02c70-5fe3-425b-af64-634d7e1187b7/jobs/135494)
* [integration](https://app.circleci.com/pipelines/github/RequestNetwork/requestNetwork/8421/workflows/74d02c70-5fe3-425b-af64-634d7e1187b7/jobs/135501)
* [utils](https://app.circleci.com/pipelines/github/RequestNetwork/requestNetwork/8573/workflows/34937b01-b8f2-43bd-b758-fe112bd500f7/jobs/137212)

---

Migrated from Asana: https://app.asana.com/0/1203912381456855/1203377996343544/f

**Comment by yomarion** [comment]
I think this test is running fine most of the time (>1/20), consider renaming the issue "flaky" for clarity.

**Comment by MantisClone** [comment]
Updated the title to clarify flakiness.
