### ISSUE TITLE
Migrate from C implementation of eccrypto to JavaScript implementation eccrypto-js

### ISSUE THREAD

**Issue by MantisClone** [RequestNetwork/requestNetwork#1207]
# Problem

C implementation of eccrypto requires compilation that is slow and takes a lot of time to build.

# Proposed Solution

Use a pure JavaScript implementation like [eccrypto-js](https://github.com/pedrouid/eccrypto-js)

**Comment by alexandre-abrioux** [comment]
This issue seems more important than before since the discovery of https://github.com/RequestNetwork/requestNetwork/issues/1227. I will try to have a look at it soon.
