### ISSUE TITLE
Setup an automatic testing tool

### ISSUE THREAD

**Issue by QuentinFchx** [RequestNetwork/requestNetwork#17]
Usually [TravisCI](https://travis-ci.com/plans) is used in open source project.
Most of the other tools ([CircleCI](https://circleci.com/pricing/), Codeship...) also have free plans.
<sub>[GitHub marketplace tools](https://github.com/marketplace/category/continuous-integration)</sub>

They're quite easy to setup and will help with PR validation!

**Comment by vrolland** [comment]
Should we close this issue, @romaric-juniet ?

**Comment by romaric-juniet** [comment]
I think we can close it. Quentin, thanks for the suggestion. We have set up Travis CI, although we still have a couple of flaky tests to take care of
