### ISSUE TITLE
@param _payees array of payees address (the index 0 will be the payee - must be msg.sender - the others are subPayees). Size must be smaller than 256.

### ISSUE THREAD

**Issue by kbapuram** [RequestNetwork/requestNetwork#38]
@param _payees array of payees address (the index 0 will be the payee - must be msg.sender - the others are subPayees). Size must be smaller than 256.

This is the comment I see on RequestCore.sol .

This hold true if the request is created as createRequestAsPayee..otherwise not :)

**Comment by vrolland** [comment]
Hello kbapuram,
Thanks to safemath [here](https://github.com/RequestNetwork/requestNetwork/blob/ceea2ba07c7ef11a67e3950e2cba986010e912da/packages/requestNetworkSmartContracts/contracts/core/RequestCore.sol#L290)  the transaction will be revert if the arrays of payees are bigger than 256.

So this is an indication for the developers of currency contracts.

Best,
