### ISSUE TITLE
Creating request from RequestCore will bypass certain validations

### ISSUE THREAD

**Issue by kbapuram** [RequestNetwork/requestNetwork#39]
We can create a Request from  **RequestCore.sol** and **createRequest** function (instead of RequestEthereum.sol). This will bypass some validations such as **require(fees == msg.value);** .This way we are able to create a request without a mandatory fee

**Comment by vrolland** [comment]
Hello,
As explains in the RequestCore documentation/comments ( [see here](https://github.com/RequestNetwork/requestNetwork/blob/ceea2ba07c7ef11a67e3950e2cba986010e912da/packages/requestNetworkSmartContracts/contracts/core/RequestCore.sol#L16) )
> Requests can only be created in the currency contracts
