### ISSUE TITLE
No validation for _expectedAmounts length

### ISSUE THREAD

**Issue by kbapuram** [RequestNetwork/requestNetwork#40]
In **RequestCore** contract and **createRequest** function, there is no validation for the length of _expectedAmounts. There is a validation for _payees.length but not for _expectedAmounts .

There will be an exception at line number 115 **( mainExpectedAmount = _expectedAmounts[0];)** if we send empty array for _expectedAmounts

**Comment by vrolland** [comment]
_payees.length and _expectedAmounts must have the same size. Otherwise, the function revert or opcode.
We improve the comments/documentation (see #42)

Thank you

**Comment by kbapuram** [comment]
The condition (payees.length and _expectedAmounts must have the same size) is not applied before we access  _expectedAmounts[0]

**Comment by vrolland** [comment]
so it will opcode

**Comment by vrolland** [comment]
Adding the check on _expectedAmounts.length will cost gas for nothing because the transaction will "op code" anyway.
Don't forget that only currency contract audited will be able to call this function.

**Comment by kbapuram** [comment]
But if you see these _expectedAmounts comes to the contract RequestEthereum from outside.This validation is missed in RequestEthereum as well.  So we need this validation in RequestCore(if you see that is why we have other validations)

**Comment by vrolland** [comment]
the validation on _payees.length allow requestCore to accept two empty arrays
