### ISSUE TITLE
Angular CLI warning when using requestNetwork.js 

### ISSUE THREAD

**Issue by giltotherescue** [RequestNetwork/requestNetwork#55]
When I run `ng serve` on a project that includes `requestNetwork.js`, I receive the following warnings:

```
WARNING in ./node_modules/requestnetworkartifacts/README.md
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| # Request_Artifacts
| Artifacts for Request Network Ethereum contracts
| 

WARNING in ./node_modules/requestnetworkartifacts/LICENSE
Module parse failed: Unexpected token (1:4)
You may need an appropriate loader to handle this file type.
| MIT License
| 
| Copyright (c) 2018 
```

It doesn't seem to hurt anything, but is annoying to see in console output every time ng reloads.

Simply deleting these files from node_modules removes the warnings.

**Comment by romaric-juniet** [comment]
Hey Gil, you already reported this issue (#49) and I'm sorry we still haven't gotten around to fixing it. I had a quick look one day, didn't manage to find the solution and now it's somewhere near the bottom of the  todo list, given that it's not that important. If you have an idea of how to fix it, I'll be happy to try it, or merge a PR :)

**Comment by giltotherescue** [comment]
So sorry for posting this twice!! I forgot. I just closed the other issue since this one has more detail.

I am not sure how to fix it, but a quick Google search shows that it is a webpack issue. Seems like there is something that can be done to exclude certain files from webpack. If we do get around to fixing it, I will be sure to send a PR :-)

**Comment by vicnicius** [comment]
I faced the same issue while working with requestNetwork yesterday. I gave it a try and tried to fix it here https://github.com/RequestNetwork/requestNetwork/pull/63.
