### ISSUE TITLE
createSignedRequest causes Metamask error 'Message length is invalid'

### ISSUE THREAD

**Issue by mikery** [RequestNetwork/requestNetwork#56]
I created a 'hello world' React app which uses `createSignedRequest`. The app is [here](https://gist.github.com/mikery/dd0552dd973e89b687496aa67dacbd10) - it is just a demo app using `create-react-app`. 

When I click the Sign button in Metamask, the Metamask popup closes and reappears. When I click Sign again, it displays the error 'message length is invalid'. It could be related to [this issue](https://github.com/MetaMask/metamask-extension/issues/1530).

Should the example in the gist work? Are there any plans to move to [signed type data](https://medium.com/metamask/scaling-web3-with-signtypeddata-91d6efc8b290)?

**Comment by romaric-juniet** [comment]
Yes, it seems to be related to the `web3.eth.sign` issue with metamask. I don't see an easy fix, I'll need to do some research for a proper solution, that can include signed type data

**Comment by romaric-juniet** [comment]
Replacing `web3.eth.sign(data, address)` with `web3.eth.personal.sign(data, address)` seems to fix the issue. Metamask doesn't require the 3rd `password` argument. I'll need to look at the consequences of the changes but in the meantime, this should unblock you

**Comment by mikery** [comment]
Thanks @romaric-juniet, `.personal.` is working. I took a shot at implementing EIP712 but it does not yet support arrays. It looks like they might be here soon: https://github.com/ethereum/EIPs/pull/1242/commits/88218efc0c7ef9091a8a474e8ab179ac51cc2673
