### ISSUE TITLE
Question: createRequestAsPayee in RequestEthereum

### ISSUE THREAD

**Issue by atvanguard** [RequestNetwork/requestNetwork#60]
Method `createRequestAsPayee` in `RequestEthereum` requires `require(msg.sender == _payeesIdAddress[0])` [here](https://github.com/RequestNetwork/requestNetwork/blob/master/packages/requestNetworkSmartContracts/contracts/synchrone/RequestEthereum.sol#L66).

I am writing a smart contract that will act as a wrapper on `createRequestAsPayee` in `RequestEthereum`. When `createRequestAsPayee` is invoked by this contract, the assertion `require(msg.sender == _payeesIdAddress[0])` always fails.

My question is: The expectation that other smart contracts might create requests on-chain wrong?

**Comment by atvanguard** [comment]
I was building this for a hackathon and as a work around, I made my smart contract emit an event and then the event listener created a request using the JS library.

**Comment by mikery** [comment]
Resolved in Slack - using the smart contract address as `payeeIdAddress`, and the recipient's address as `payeePaymentAddress` works as expected.

**Comment by atvanguard** [comment]
Thanks @mikery
