### ISSUE TITLE
Question: Invoice API

### ISSUE THREAD

**Issue by peat85** [RequestNetwork/requestNetwork#725]
Is it possible to set a request.network customer id (i.e. the same ID as used in the "InvoiceMe" feature) directly in the invoice data sent to `POST https://api.request.network/invoices` so that the invoice is sent automatically to the customer once it is "on-chain"?

If so, what is this field called?

If not, how is the customer supposed to be notified about the invoice? The Invoice API docs state:

> Whenever an invoice is created, it is possible to have an email sent to the designated payer. 

How do i make use of this possibility? When creating an invoice over the test network i did not reveice any emails despite the `email` field being set in `buyerInfo`.

Thanks!

**Comment by yomarion** [comment]
It's not possible to invoice a customer ID.
It's true that we manually whitelist the domains allowed to send notifications, can you please reach to us on Discord https://discord.gg/md3j4x9a to discuss further? You can tag me or DM me @yomarion

I close this issue as it concerns our API service and not the protocol.
